migrated to @roxi/routify
silinternational/the-way-svelte pull request #2
Opened 2021-07-04 00:10 UTC by hobbitronics

2021-07-05 20:01 UTC, longrunningprocess requested changes
the `sveltech` to `@roxi` makes sense but some of the `.routify/*` files are either not needed or an unfortunate configuration now necessary...

2021-07-05 20:01 UTC, longrunningprocess commented on .routify/routes.js
> +
are you certain this one should be checked in?

2021-07-05 22:51 UTC, hobbitronics commented on .routify/routes.js
> +
When I build it generates this. The migration guide gives two options:
routifyDir has been defaulted to .routify.
Option A) Update to import { routes } from '../.routify/routes' in App.svelte
Option B) Set routifyDir to node_modules/@roxi/routify/tmp/routes.

2021-07-05 23:03 UTC, hobbitronics commented on rollup.config.js
> +	inlineDynamicImports: true,
instead of this we could add
  ```"routify": {
    "dynamicImports": false
  }```
to the package.json. Not sure which is preferable.

2021-07-05 23:36 UTC, hobbitronics commented on rollup.config.js
> +	inlineDynamicImports: true,
I decided to go with the suggestion made in the issue [here](https://github.com/roxiness/routify.dev/issues/218)

2021-07-06 00:39 UTC, longrunningprocess approved these changes
this is much better

2021-07-06 13:43 UTC, merged

2021-07-06 13:43 UTC, Schparky approved these changes